SET C51INC=D:\Program Files\Keil\C51\Inc;D:\Program Files\Keil\C51\Inc\Atmel
SET C51LIB=D:\Program Files\Keil\C51\Lib
SET CPU_TYPE=AT89C51
SET CPU_VENDOR=Microchip
SET UV2_TARGET=main
SET CPU_XTAL=0x00A8C000
"D:\Program Files\Keil\C51\BIN\A51.EXE" @".\Objects\STARTUP._ia"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\APP_HO~1.__I"
"D:\Program Files\Keil\C51\BIN\A51.EXE" @".\Objects\os_cpu_a._ia"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\os_cpu_c.__i"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\os_flag.__i"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\os_mbox.__i"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\os_mem.__i"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\os_mutex.__i"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\os_q.__i"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\os_sem.__i"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\os_task.__i"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\os_time.__i"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\os_tmr.__i"
"D:\Program Files\Keil\C51\BIN\C51.EXE" @".\Objects\os_core.__i"
"D:\Program Files\Keil\C51\BIN\BL51.EXE" @".\Objects\main.lnp"
